### PR TITLE
Fix issue #78 (GC problem when version number > limit)

### LINKED ISSUE #78: GC problem when version number > limit, then matching by access_key can fail

### PR DESCRIPTION
**Pull request by mlaflamm**
Closes #78

### CODE REVIEW

File: mry-core/src/main/scala/com/wajam/mry/storage/mysql/MysqlStorage.scala [hunk 1]
```diff
@@ -414,7 +414,12 @@ class MysqlStorage(config: MysqlStorageConfiguration, garbageCollection: Boolean
                   record.versionsCount = reloaded.versionsCount
                 }
                 case _ => {
-                  warn("Record version not found found (tk={}, path={})", record.token, record.accessPath)
+                  warn("Record version not found (table={}, tk={}, path={})", table.name, record.token, record.accessPath)
+
+                  // The access path we were trying to GC is beyond the version batch size i.e. if the batch is 100,
+                  // we were trying the GC the 101st or later. Clearing the cache, will restart GC to the first range
+                  // of access path for the same token.
+                  tableVersionsCache.clear()
```
Comment (mlaflamm) [inline mry-core/src/main/scala/com/wajam/mry/storage/mysql/MysqlStorage.scala:422]: FYI, this is the only real change. The other changes were to repro the problem in an integration test.

**Comment by coderunner** [comment]
+1
